name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  SOLUTION_FILE: './CICD_API/CICD_API.sln'
  FOLDER: './CICD_API'


jobs:
  build:
    runs-on: ubuntu-latest
    environment: Azure

    steps:                        
      - name: Checkout code 💫
        uses: actions/checkout@v4

      - name: Setup dotnet 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies 📦
        run: dotnet restore ${{ env.FOLDER }}

      - name: Build App
        run: dotnet build -c Release --no-restore ${{ env.SOLUTION_FILE }}

      - name: Publish App
        run: dotnet publish -c Release -o ./out ${{ env.SOLUTION_FILE }}

      - name: Deploy to Azure Web Apps
        uses: azure/webapps-deploy@v2
        with:
          app-name: daveq-cicd
          publish-profile: ${{ secrets.AZURE_THE_DARK_SECRET_OF_THE_ORTHODOX_CHURCH }}
          package: ./out